mutation CheckoutCustomerNoteUpdate($input: CheckoutCustomerNoteUpdateInput!) {
  checkoutMutation {
    checkoutCustomerNoteUpdate(input: $input) {
      id
      createdAt
      updatedAt
      totalQuantity
      cost {
        totalDiscountAmount { amount currencyCode }
        totalTaxAmount { amount currencyCode }
        totalShippingAmount { amount currencyCode }
        subtotalAmount {
          amount
          currencyCode
        }
        totalAmount {
          amount
          currencyCode
        }
      }
      customerIdentity { email phone countryCode customer { id } }
      customerNote
      deliveryGroups {
        id
        checkoutLines { id }
        deliveryAddress { id address1 address2 city countryCode provinceCode postalCode email firstName lastName data }
        deliveryMethods { code deliveryMethodType provider { code data } }
        selectedDeliveryMethod { code deliveryMethodType provider { code data } }
        estimatedCost { amount { amount currencyCode } paymentModel }
      }
      appliedPromoCodes {
        code
        appliedAt
      }
    }
  }
}
